version: "3.7"

services:

  deploy-conda-community:
    image: lsstts/deploy-env:${CYCLE}
    build:
      context: ../build/
      dockerfile: ./deploy-env/conda/Dockerfile
      labels:
        com.description: "Base deployment image for cycle/revision ${CYCLE}."
      args:
        dds_community_version: ${dds_community_version}
        dds_community_build: ${dds_community_build_el7}
        ts_salobj: ${ts_salobj}
        ts_dds: ${ts_dds_community}
        ts_idl: ${ts_idl}

  deploy-conda-community-aarch64:
    image: lsstts/deploy-env-aarch64:${CYCLE}
    build:
      context: ../build/
      dockerfile: ./deploy-env/conda-aarch64/Dockerfile
      labels:
        com.description: "Base aarch64 deployment image for cycle/revision ${CYCLE}."
      args:
        dds_community_version: ${dds_community_version}
        ts_salobj: ${ts_salobj}
        ts_dds: ${ts_dds_community}
        ts_idl: ${ts_idl}

  deploy-conda-private:
    image: ts-dockerhub.lsst.org/deploy-env:${CYCLE}
    build:
      context: ../build/
      dockerfile: ./deploy-env/conda/Dockerfile
      labels:
        com.description: "Base deployment image for cycle ${CYCLE}."
      args:
        dds_community_version: ${dds_community_version}
        dds_community_build: ${dds_community_build_el7}
        dds_private_version: ${dds_private_version}
        dds_private_build: ${dds_private_build}
        ts_dds: ${ts_dds_private}
        ts_ddsconfig: ${ts_ddsconfig}
        ts_idl: ${ts_idl}_${ts_xml}_${ts_sal}
        ts_salobj: ${ts_salobj}

  deploy-lsstsqre-community:
    image: lsstts/deploy-sqre:${CYCLE}
    build:
      context: ../build/
      dockerfile: ./deploy-env/lsstsqre/Dockerfile
      labels:
        com.description: "Base deployment image for cycle ${CYCLE}."
      args:
        image_tag: ${lsstsqre}
        dds_community_version: ${dds_community_version}
        dds_community_build: ${dds_community_build_el7}
        ts_salobj: ${ts_salobj}
        ts_dds: ${ts_dds_community}

  deploy-lsstsqre-private:
    image: ts-dockerhub.lsst.org/deploy-sqre:${CYCLE}
    build:
      context: ../build/
      dockerfile: ./deploy-env/lsstsqre/Dockerfile
      labels:
        com.description: "Base deployment image for cycle ${CYCLE}."
      args:
        image_tag: ${lsstsqre}
        dds_community_version: ${dds_community_version}
        dds_community_build: ${dds_community_build_el7}
        dds_private_version: ${dds_private_version}
        dds_private_build: ${dds_private_build}
        ts_salobj: ${ts_salobj}
        ts_dds: ${ts_dds_private}
        ts_idl: ${ts_idl}_${ts_xml}_${ts_sal}
        ts_ddsconfig: ${ts_ddsconfig}

  base-sqre-community:
    image: lsstts/base-sqre:${CYCLE}
    build:
      context: ../build/
      dockerfile: ./develop-env/lsstsqre/Dockerfile
      labels:
        com.description: "LSST Telescope and Site base development for cycle/revision ${CYCLE}."
      args:
        image_tag: ${lsstsqre}
        dds_community_version: ${dds_community_version}
        dds_community_build: ${dds_community_build}
        ts_dds: ${ts_dds_community}
        UID: ${UID}
        GID: ${GID}

  base-sqre-private:
    image: ts-dockerhub.lsst.org/base-sqre:${CYCLE}
    build:
      context: ../build/
      dockerfile: ./develop-env/lsstsqre/Dockerfile
      labels:
        com.description: "LSST Telescope and Site base development for cycle/revision ${CYCLE}."
      args:
        image_tag: ${lsstsqre}
        dds_community_version: ${dds_community_version}
        dds_community_build: ${dds_community_build}
        dds_private_version: ${dds_private_version}
        dds_private_build: ${dds_private_build}
        UID: ${UID}
        GID: ${GID}

  salobj-community:
    image: lsstts/salobj:${CYCLE}${rev}
    build:
      context: ../build/develop-env/salobj/
      network: ${build_network}
      labels:
        com.description: LSST Telescope and Site Docker image with SalObj for cycle/revision ${CYCLE}${rev}.
      args:
        hub: lsstts
        base_image_tag: ${CYCLE}
        ts_dds: ${ts_dds_community}=${ts_dds_community_conda_build}
        ts_config_ocs: ${ts_config_ocs}
        ts_config_attcs: ${ts_config_attcs}
        ts_config_mtcalsys: ${ts_config_mtcalsys}
        ts_config_eas: ${ts_config_eas}
        ts_config_latiss: ${ts_config_latiss}
        ts_config_mttcs: ${ts_config_mttcs}
        ts_config_atcalsys: ${ts_config_atcalsys}
        ts_ddsconfig: ${ts_ddsconfig}
        ts_xml: ${ts_xml}
        ts_idl: ${ts_idl}
        ts_sal: ${ts_sal}
        ts_salobj: ${ts_salobj}

  salobj-private:
    image: ts-dockerhub.lsst.org/salobj:${CYCLE}${rev}
    build:
      context: ../build/develop-env/salobj/
      labels:
        com.description: LSST Telescope and Site Docker image with SalObj for cycle/revision ${CYCLE}${rev}.
      args:
        hub: ts-dockerhub.lsst.org
        base_image_tag: ${CYCLE}
        ts_dds: ${ts_dds_private}
        ts_config_ocs: ${ts_config_ocs}
        ts_config_attcs: ${ts_config_attcs}
        ts_config_mtcalsys: ${ts_config_mtcalsys}
        ts_config_eas: ${ts_config_eas}
        ts_config_latiss: ${ts_config_latiss}
        ts_config_mttcs: ${ts_config_mttcs}
        ts_config_atcalsys: ${ts_config_atcalsys}
        ts_ddsconfig: ${ts_ddsconfig}
        ts_xml: ${ts_xml}
        ts_idl: ${ts_idl}
        ts_sal: ${ts_sal}
        ts_salobj: ${ts_salobj}

  develop-env-community:
    image: lsstts/develop-env:${CYCLE}${rev}${rev}
    build:
      context: ../build/develop-env/develop-env/
      network: ${build_network}
      labels:
        com.description: LSST Telescope and Site development environment image for cycle/revision ${CYCLE}${rev}..
      args:
        hub: lsstts
        base_image_tag: ${CYCLE}${rev}
        ts_scriptqueue: ${ts_scriptqueue}
        ts_observatory_control: ${ts_observatory_control}
        ts_standardscripts: ${ts_standardscripts}
        ts_externalscripts: ${ts_externalscripts}
        ts_ATMCSSimulator: ${ts_ATMCSSimulator}
        ts_ATDome: ${ts_ATDome}
        ts_ATDomeTrajectory: ${ts_ATDomeTrajectory}
        ts_simactuators: ${ts_simactuators}
        ts_hexrotcomm: ${ts_hexrotcomm}

  develop-env-private:
    image: ts-dockerhub.lsst.org/develop-env:${CYCLE}${rev}
    build:
      context: ../build/develop-env/develop-env/
      network: ${build_network}
      labels:
        com.description: LSST Telescope and Site development environment image for cycle/revision ${CYCLE}${rev}..
      args:
        hub: ts-dockerhub.lsst.org
        base_image_tag: ${CYCLE}${rev}
        ts_scriptqueue: ${ts_scriptqueue}
        ts_observatory_control: ${ts_observatory_control}
        ts_standardscripts: ${ts_standardscripts}
        ts_externalscripts: ${ts_externalscripts}
        ts_ATMCSSimulator: ${ts_ATMCSSimulator}
        ts_ATDome: ${ts_ATDome}
        ts_ATDomeTrajectory: ${ts_ATDomeTrajectory}
        ts_simactuators: ${ts_simactuators}
        ts_hexrotcomm: ${ts_hexrotcomm}

  bare-centos-community:
    image: lsstts/centos7:${CYCLE}
    build:
      context: ../build/
      dockerfile: ./develop-env/bare-centos/Dockerfile
      labels:
        com.description: "LSST Telescope and Site base CentOS 7 image for cycle ${CYCLE}."
      args:
        dds_community_version: ${dds_community_version}
        dds_community_build: ${dds_community_build_el7}
        ts_xml: ${ts_xml}
        ts_sal: ${ts_sal}

  conda-builder-aarch64-community:
    image: lsstts/centos7-aarch64:${CYCLE}
    build:
      context: ../build/
      dockerfile: ./conda_builder/aarch64/Dockerfile
      labels:
        com.description: "LSST Telescope and Site base CentOS 7 aarch64 image for cycle ${CYCLE}."
      args:
        dds_community_version: ${dds_community_version}

  conda-builder-community:
    image: lsstts/conda_package_builder:${CYCLE}
    build:
      context: ../build/
      dockerfile: ./conda_builder/linux64/Dockerfile
      labels:
        com.description: "LSST Telescope and Site base CentOS 7 linux64 image for cycle ${CYCLE}."
      args:
        dds_community_version: ${dds_community_version}

  conda-builder-private:
    image: ${hub}/conda_package_builder:${CYCLE}
    build:
      context: ../build/
      dockerfile: ./conda_builder/linux64/Dockerfile
      labels:
        com.description: "LSST Telescope and Site base CentOS 7 linux64 image for cycle ${CYCLE}."
      args:
        dds_community_version: ${dds_community_version}
        dds_community_build: ${dds_community_build_el7}
        dds_private_version: ${dds_private_version}
        dds_private_build: ${dds_private_build}

  aos_aoclc:
    image: ${hub}/aos_aoclc:${CYCLE}${rev}
    build:
      context: ../build/aos_aoclc
      labels:
        com.description: "AOS AOCL image for cycle/revision ${CYCLE}${rev}."
        phosim_utils: ${phosim_utils}
        ts_wep: ${ts_wep}
        ts_ofc: ${ts_ofc}
      args:
        hub: ${hub}
        IMAGE_TAG: ${CYCLE}${rev}
        phosim_utils: ${phosim_utils}
        ts_wep: ${ts_wep}
        ts_ofc: ${ts_ofc}

  lsst_sims:
    image: ${hub}/lsst_sims:${CYCLE}${rev}
    build:
      context: ../build/lsst_sims
      labels:
        com.description: "LSST sims image for cycle/revision ${CYCLE}${rev}."
      args:
        hub: ${hub}
        base_image_tag: ${CYCLE}${rev}
        lsst_sims: ${lsst_sims}

  dimm:
    image: ${hub}/dimm:${CYCLE}${rev}
    build:
      context: ../build/dimm
      labels:
        com.description: "DIMM deployment image for cycle/revision ${CYCLE}${rev}."
      args:
        deploy_env: ${hub}/${deploy_env}
        deploy_tag: ${CYCLE}
        dimm: ${ts_dimm}
        config: ${ts_config_ocs}
  dsm:
    image: ${hub}/dsm:${CYCLE}${rev}
    build:
      context: ../build/dsm
      labels:
        com.description: "DSM deployment image for cycle/revision ${CYCLE}${rev}."
      args:
        hub: ${hub}
        cycle: ${CYCLE}
        dsm: ${ts_dsm}

  mtaos_sim:
    image: ${hub}/mtaos_sim:${CYCLE}${rev}
    build:
      context: ../build/
      dockerfile: ./mtaos_sim/Dockerfile
      labels:
        com.description: "MTAOS simulator deployment image for cycle/revision ${CYCLE}${rev}."
      args:
        hub: ${hub}
        cycle: ${CYCLE}
        phosim_utils: ${phosim_utils}
        ts_wep: ${ts_wep}
        ts_ofc: ${ts_ofc}
        mtaos: ${ts_mtaos}
        ts_config_mttcs: ${ts_config_mttcs}

  mtdome:
    image: ${hub}/mtdome:${CYCLE}${rev}
    build:
      context: ../build/mtdome
      labels:
        com.description: "MTDome component for cycle {$CYCLE}"
      args:
        cycle: ${CYCLE}
        hub: ${hub}
        mtdome: ${ts_mtdome}
        config: ${ts_config_mttcs}

  mtdometrajectory:
    image: ${hub}/mtdometrajectory:${CYCLE}${rev}
    build:
      context: ../build/mtdometrajectory
      labels:
        com.description: "MTDomeTrajectory component for cycle {$CYCLE}"
      args:
        cycle: ${CYCLE}
        hub: ${hub}
        mtdometrajectory: ${ts_mtdometrajectory}
        config: ${ts_config_mttcs}

  mthexapod:
    image: ${hub}/mthexapod:${CYCLE}${rev}
    build:
      context: ../build/mthexapod
      labels:
        com.description: "MTHexapod deployment image for cycle/revision ${CYCLE}${rev}."
      args:
        deploy_env: ${hub}/${deploy_env}
        deploy_tag: ${CYCLE}
        mthexapod: ${ts_mthexapod}
        hexrotcomm: ${ts_hexrotcomm}
        config: ${ts_config_mttcs}

  mtm1m3_sim:
    image: ${hub}/mtm1m3_sim:${CYCLE}${rev}
    build:
      context: ../build/
      dockerfile: ./mtm1m3_sim/Dockerfile
      labels:
        com.description: "M1M3 simulator deployment image for cycle/revision ${CYCLE}${rev}."
        sal: ${ts_sal}
        xml: ${ts_xml}
        m1m3: ${ts_m1m3support}
      args:
        cycle: ${CYCLE}
        hub: ${hub}
        rpm: ${ts_xml}-${ts_sal}.el7.x86_64
        m1m3: ${ts_m1m3support}

  mtm2_sim:
    image: ${hub}/m2:${CYCLE}${rev}
    build:
      context: ../build/mtm2_sim
      labels:
        com.description: "M2 simulator deployment image for cycle/revision ${CYCLE}${rev}."
      args:
        deploy_env: ${hub}/${deploy_env}
        deploy_tag: ${CYCLE}
        m2: ${ts_m2}
        config: v${ts_config_mttcs}

  mtmount:
    image: ${hub}/mtmount:${CYCLE}${rev}
    build:
      context: ../build/mtmount
      labels:
        com.description: "MTmount deployment image for cycle/revision ${CYCLE}${rev}."
      args:
        deploy_env: ${hub}/${deploy_env}
        deploy_tag: ${CYCLE}
        mtmount: ${ts_mtmount}
        hexrotcomm: ${ts_hexrotcomm}
        config: v${ts_config_mttcs}

  mtrotator:
    image: ${hub}/mtrotator:${CYCLE}${rev}
    build:
      context: ../build/mtrotator
      labels:
        com.description: "MTRotator deployment image for cycle/revision ${CYCLE}${rev}."
      args:
        deploy_env: ${hub}/${deploy_env}
        deploy_tag: ${CYCLE}
        mtrotator: ${ts_mtrotator}
        hexrotcomm: ${ts_hexrotcomm}
        config: ${ts_config_mttcs}

  ptg:
    image: ts-dockerhub.lsst.org/ptkernel:${CYCLE}${rev}
    build:
      context: ../build/
      dockerfile: ./ptg/Dockerfile
      labels:
        com.description: "Pointing component deployment image for cycle/revision ${CYCLE}${rev}."
        rpm: 0:${ts_xml}-${ts_sal}.el7.x86_64
        ptg: ${ts_pointing_common}
      args:
        cycle: ${CYCLE}
        hub: ${hub}
        rpm: 0:${ts_xml}-${ts_sal}.el7.x86_64
        ptg: ${ts_pointing_common}

  salkafka:
    image: ${hub}/salkafka:${CYCLE}${rev}
    build:
      context: ../build/salkafka
      labels:
        com.description: "SAL kafka producers deployment image for cycle/revision ${CYCLE}${rev}."
        deploy_env: ${deploy_env}
        deploy_tag: ${CYCLE}
        salkafka: ${ts_salkafka}
      args:
        deploy_env: ${hub}/${deploy_env}
        deploy_tag: ${CYCLE}
        salkafka: ${ts_salkafka}

  scheduler:
    image: ${hub}/scheduler:${CYCLE}${rev}
    build:
      context: ../build/scheduler
      labels:
        com.description: "Scheduler image for cycle/revision ${CYCLE}${rev}"
      args:
        hub: ${hub}
        deploy_tag: ${CYCLE}
        ts_config_ocs: ${ts_config_ocs}
        ts_idl: ${ts_idl}
        ts_scriptqueue: ${ts_scriptqueue}
        ts_scheduler: ${ts_scheduler}

  scriptqueue:
    image: ${hub}/scriptqueue:${CYCLE}${rev}
    build:
      context: ../build/
      dockerfile: ./scriptqueue/Dockerfile
      labels:
        com.description: "Script queue image for cycle/revision ${CYCLE}${rev}."
      args:
        hub: ${hub}
        deploy_tag: ${CYCLE}
        ts_config_attcs: ${ts_config_attcs}
        ts_config_ocs: ${ts_config_ocs}
        cwfs: ${cwfs}
        Spectractor: ${Spectractor}
        obs_base: ${obs_base}
        pipe_tasks: ${pipe_tasks}
        rapid_analysis: ${rapid_analysis}
        atmospec: ${atmospec}
        ts_observing_utilities: ${ts_observing_utilities}
        ts_observatory_control: ${ts_observatory_control}
        ts_externalscripts: ${ts_externalscripts}
        ts_standardscripts: ${ts_standardscripts}
        ts_scriptqueue: ${ts_scriptqueue}
        ts_idl: ${ts_idl}
        ts_atdome: ${ts_ATDome}
        ts_atdometrajectory: ${ts_ATDomeTrajectory}
        ts_atmcssimulator: ${ts_ATMCSSimulator}

  test:
    image: ${hub}/test:${CYCLE}${rev}
    build:
      context: ../build/test
      labels:
        com.description: "Test CSC for cycle/revision ${CYCLE}${rev}."
        deploy_env: ${deploy_env}
        deploy_tag: ${CYCLE}
      args:
        deploy_env: ${hub}/${deploy_env}
        deploy_tag: ${CYCLE}

  watcher:
    image: ${hub}/watcher:${CYCLE}${rev}
    build:
      context: ../build/watcher
      labels:
        com.description: "Watcher CSC for cycle/revision ${CYCLE}${rev}."
      args:
        deploy_env: ${hub}/${deploy_env}
        deploy_tag: ${CYCLE}
        config_ocs: ${ts_config_ocs}
        watcher: ${ts_watcher}

  weatherstation:
    image: ${hub}/weatherstation:${CYCLE}${rev}
    build:
      context: ../build/weatherstation
      labels:
        com.description: "Weather Station CSC for cycle/revision ${CYCLE}${rev}."
      args:
        deploy_env: ${hub}/${deploy_env}
        deploy_tag: ${CYCLE}
        config: ${ts_config_ocs}
        weatherstation: ${ts_weatherstation}

  ospl-daemon:
    image: ${hub}/ospl-daemon:${CYCLE}${rev}
    build:
      context: ../build/ospl-daemon
      labels:
        com.description: "OSPL Daemon for cycle/revision ${CYCLE}${rev}."
        deploy_env: ${deploy_env}
        deploy_tag: ${CYCLE}
      args:
        deploy_env: ${hub}/${deploy_env}
        deploy_tag: ${CYCLE}

  atmcs_sim:
    image: ${hub}/atmcs_sim:${CYCLE}${rev}
    build:
      context: ../build/atmcs_sim
      labels:
        com.description: "ATMCS simulator for cycle {$CYCLE}"
      args:
        cycle: ${CYCLE}
        hub: ${hub}
        atmcs: ${ts_ATMCSSimulator}

  atdome:
    image: ${hub}/atdome:${CYCLE}${rev}
    build:
      context: ../build/atdome
      labels:
        com.description: "ATDome component for cycle {$CYCLE}"
      args:
        cycle: ${CYCLE}
        hub: ${hub}
        atdome: ${ts_ATDome}
        config: ${ts_config_attcs}

  atdometrajectory:
    image: ${hub}/atdometrajectory:${CYCLE}${rev}
    build:
      context: ../build/atdometrajectory
      labels:
        com.description: "ATDomeTrajectory component for cycle {$CYCLE}"
      args:
        cycle: ${CYCLE}
        hub: ${hub}
        atdometrajectory: ${ts_ATDomeTrajectory}
        config: ${ts_config_attcs}

  atpneumatics_sim:
    image: ${hub}/at_pneumatics_sim:${CYCLE}${rev}
    build:
      context: ../build/atpneumatics_sim
      labels:
        com.description: "ATPneumatics simulator for cycle {$CYCLE}"
      args:
        cycle: ${CYCLE}
        hub: ${hub}
        atpneumatics_sim: ${ts_ATPneumaticsSimulator}

  ataos:
    image: ${hub}/ataos:${CYCLE}${rev}
    build:
      context: ../build/ataos
      dockerfile: ./Dockerfile.conda
      labels:
        com.description: "ATAOS component for cycle {$CYCLE}"
      args:
        cycle: ${CYCLE}
        hub: ${hub}
        ts_ataos: ${ts_ataos}
        config: ${ts_config_attcs}
        ts_observatory_control: ${ts_observatory_control}

  athexapod:
    image: ${hub}/athexapod:${CYCLE}${rev}
    build:
      context: ../build/athexapod
      labels:
        com.description: "ATHexapod component for cycle {$CYCLE}"
      args:
        cycle: ${CYCLE}
        hub: ${hub}
        athexapod: ${ts_athexapod}
        config: ${ts_config_attcs}

  atspectrograph:
    image: ${hub}/atspec:${CYCLE}${rev}
    build:
      context: ../build/atspectrograph
      labels:
        com.description: "ATSpectrograph component for cycle {$CYCLE}"
      args:
        cycle: ${CYCLE}
        hub: ${hub}
        atspec: ${ts_atspec}
        config: ${ts_config_latiss}
