{% set data = load_setup_py_data(setup_file='../setup.py', from_recipe_dir=True) %}
package:
  name: ts-cycle
  version: {{ data.get('version') }}

requirements:
  run:
    - ts-salobj =={{ data.get('ts_salobj_version') }}
    - ts-xml =={{ data.get('ts_xml_version')}}
    - python
